services:
  db:
    image: postgres:16.3
    container_name: koombea_db
    networks:
      - nw_koombea
    restart: always
    volumes:
      - data:/var/lib/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: koombea_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    networks:
      - nw_koombea
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
networks:
  nw_koombea:
    driver: bridge
volumes:
  data: